# Generated by Django 2.1 on 2018-12-20 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=3)),
                ('points', models.DecimalField(decimal_places=0, max_digits=10)),
                ('latest_order_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=5)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient_offerd_by_supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=0, max_digits=5)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=3)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=5)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order_has_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cup_size', models.CharField(max_length=10)),
                ('ice_level', models.CharField(max_length=10)),
                ('sugar_level', models.CharField(max_length=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Product_made_by_ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=5)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.Ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=20)),
                ('supplier_address', models.CharField(blank=True, max_length=50)),
                ('supplier_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='ingredient',
            field=models.ManyToManyField(through='drink.Product_made_by_ingredient', to='drink.Ingredient'),
        ),
        migrations.AddField(
            model_name='order_has_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(through='drink.Order_has_product', to='drink.Product'),
        ),
        migrations.AddField(
            model_name='ingredient_offerd_by_supplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.Supplier'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='supplier',
            field=models.ManyToManyField(through='drink.Ingredient_offerd_by_supplier', to='drink.Supplier'),
        ),
    ]
