# Generated by Django 2.1 on 2019-01-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0003_auto_20190105_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='latest_order_time',
            field=models.DateTimeField(),
        ),
    ]
