# Generated by Django 2.1 on 2019-01-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0004_auto_20190105_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_has_product',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
