# Generated by Django 2.1.3 on 2019-01-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0008_so_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='S0_Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=20)),
                ('d', models.FloatField()),
                ('sigma', models.FloatField()),
                ('accepted_risk', models.FloatField()),
                ('S0', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='SO_Parameters',
        ),
        migrations.AddField(
            model_name='rop_parameters',
            name='ROP',
            field=models.FloatField(default=0),
        ),
    ]
