# Generated by Django 2.1.3 on 2019-01-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0009_auto_20190107_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='is_sufficient',
        ),
    ]
